name: Go
on: [push]
jobs:
  golangci:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v3
        with:
          go-version: 1.17
      - uses: actions/checkout@v3

      - name: Setup
        run: make setup

      - name: Get dependencies
        run: make deps

      - name: Generate mocks
        run: |
          go generate
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
        with:
          # Optional: version of golangci-lint to use in form of v1.2 or v1.2.3 or `latest` to use the latest version
          version: latest

  unit-tests:
    name: Run Unit Tests
    runs-on: ubuntu-latest
    steps:
    - name: Download Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.18
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v2

    - name: Setup
      run: make setup

    - name: Get dependencies
      run: make deps

    - name: Generate mocks
      run: |
        go generate

    - name: Test
      run: make test-unit

    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        files: coverage.out
